/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.openbravo.pos.inventory;

import com.openbravo.basic.BasicException;
import com.openbravo.pos.forms.AppLocal;
import com.openbravo.pos.forms.DataLogicSales;
import com.openbravo.pos.ticket.IngredientInfo;
import com.openbravo.pos.ticket.ProductMini;
import java.awt.Dimension;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author AVM
 */
public class ComplexProductsEditor extends javax.swing.JDialog {

    /**
     * Creates new form ComplexProductsEditor
     */
    private final int FRAME_WIDTH = 500;
    private final int FRAME_HEIGHT = 380;
    public ComplexProductsEditor(DataLogicSales m_dSales, Object id) {
        
        initComponents();
        setModalityType(ModalityType.APPLICATION_MODAL);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int locationX = (screenSize.width - FRAME_WIDTH) / 2;
        int locationY = (screenSize.height - FRAME_HEIGHT) / 2;
        setBounds(new Rectangle(locationX, locationY, FRAME_WIDTH, FRAME_HEIGHT));        
        //setDefaultCloseOperation(HIDE_ON_CLOSE);
        setSize(FRAME_WIDTH,FRAME_HEIGHT);
        setTitle(AppLocal.getIntString("title.editRecept"));
        setResizable(false);
        
        List<ProductMini> productMiniList = new ArrayList<>();
        try {
            productMiniList = m_dSales.getAllProductName();
        } catch (BasicException ex) {
            Logger.getLogger(ComplexProductsEditor.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jTable_ProductList.setModel(new DefaultTableModel(new String [] {
                    "ID","Продукт", "Коэфициент"
                }, productMiniList.size()));
//                }, 1));
        jTable_ProductList.getColumnModel().getColumn(0).setResizable(false);
        jTable_ProductList.getColumnModel().getColumn(0).setPreferredWidth(0);
        jTable_ProductList.getColumnModel().getColumn(0).setMinWidth(0);
        jTable_ProductList.getColumnModel().getColumn(0).setMaxWidth(0);
        jTable_ProductList.getColumnModel().getColumn(1).setResizable(false);
        jTable_ProductList.getColumnModel().getColumn(2).setResizable(false);
        int row = 0;
        for (ProductMini productMini : productMiniList) {
            jTable_ProductList.setValueAt(productMini.getId(), row, 0);
            jTable_ProductList.setValueAt(productMini.getIngredientName(), row, 1);
            jTable_ProductList.setValueAt(productMini.isIsComplex(), row, 2);
//            jTable_ProductList.setValueAt("qwerty", 0, 0);
//            jTable_ProductList.setValueAt("Вася", 0, 1);
//            jTable_ProductList.setValueAt(productMiniList.size(), 0, 2);
            row++;
        }
        
        
        
        List<IngredientInfo> ingredients = new ArrayList<>();
        
        try {
            ingredients = m_dSales.getIngredients((String)id);
        } catch (BasicException ex) {
            Logger.getLogger(ComplexProductsEditor.class.getName()).log(Level.SEVERE, null, ex);
        }

        final String[] list1ModelData = new String[ingredients.size()];
        for (int i = 0; i < ingredients.size(); i++) {
            list1ModelData[i] = ingredients.get(i).getIngredientName();
        }
        
        
        jList_Ingredient.setModel(new javax.swing.AbstractListModel<String>() {
            @Override
            public int getSize() { return list1ModelData.length; }
            @Override
            public String getElementAt(int i) { return list1ModelData[i]; }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList_Ingredient = new javax.swing.JList<>();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_ProductList = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jList_Ingredient.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Продукт1", "Продукт2", "Продукт3", "Продукт4", "Продукт5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList_Ingredient);

        jToggleButton1.setText("<<<");

        jToggleButton2.setText(">>>");

        jLabel1.setText(AppLocal.getIntString("editRecept.toRecept"));

        jLabel2.setText(AppLocal.getIntString("editRecept.available"));

        jTable_ProductList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"id1","Кофе", "0,25"},
                {"id1","Сахар", "0,02"},
                {"id1","Молоко", "0,03"},
                {"id1","Молоко1", "0,03"},
                {"id1","Молоко2", "0,03"},
                {"id1","Молоко3", "0,03"},
                {"id1","Молоко4", "0,03"},
                {"id1","Молоко5", "0,03"},
                {"id1","Молоко6", "0,03"},
                {"id1","Молоко7", "0,03"},
                {"id1","Молоко8", "0,03"}
            },
            /*new String [] {
                "Продукт", "Коэфициент"
            }*/
            new String [] {
                new String("ID"),
                AppLocal.getIntString("column.product"),
                AppLocal.getIntString("column.coefficient")
            }
        ));
        jTable_ProductList.setEnabled(true);
        jScrollPane2.setViewportView(jTable_ProductList);

        jButton1.setText(AppLocal.getIntString("button.doneEdit"));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jToggleButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                    .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton2))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    
    /*public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComplexProductsEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }


      
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ComplexProductsEditor().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList_Ingredient;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable_ProductList;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
